# Generated by Django 5.2.17 on 2026-10-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(db_column='ID_USER', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isAdm', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuário',
                'db_table': 'User',
            },
        ),
    ]
