# Generated by Django 5.2.17 on 2026-10-09 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.CharField(db_column='ID_ESP', max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('gasolineLevel', models.FloatField(default=0)),
                ('tankCapacity', models.FloatField(default=0)),
                ('fuelConsumptionFactor', models.FloatField(default=0)),
                ('totalDistance', models.FloatField(default=0)),
                ('tripConsumption', models.FloatField(default=0)),
                ('sync_version', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'VehicleData',
            },
        ),
        migrations.CreateModel(
            name='UserVehicleData',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(db_column='ID_USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(db_column='ID_ESP', on_delete=django.db.models.deletion.CASCADE, to='devices.vehicledata')),
            ],
            options={
                'db_table': 'User-VehicleData',
                'constraints': [models.UniqueConstraint(fields=('device', 'user'), name='unique_user_device')],
            },
        ),
    ]
