# Generated by Django 5.2.17 on 2026-09-28 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters_inserted', models.FloatField(verbose_name='litros inseridos no carro')),
                ('liters_spent_system', models.FloatField(verbose_name='litros gastos no sistema')),
                ('old_factor', models.FloatField(verbose_name='fator antigo')),
                ('new_factor', models.FloatField(verbose_name='fator novo')),
                ('gasoline_level_before', models.FloatField(verbose_name='nível antes (L)')),
                ('gasoline_level_after', models.FloatField(verbose_name='nível depois (L)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuels', to='telemetry.vehicle')),
            ],
            options={
                'verbose_name': 'abastecimento',
                'verbose_name_plural': 'abastecimentos',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
