# Generated by Django 5.2.17 on 2026-09-28 23:10

import django.db.models.deletion
import telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=17, unique=True, validators=[telemetry.models.validate_device_id], verbose_name='ID do dispositivo (MAC)')),
                ('name', models.CharField(max_length=100, verbose_name='apelido do veículo')),
                ('plate', models.CharField(blank=True, max_length=10, verbose_name='placa')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='nome do dono')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tank_capacity', models.FloatField(default=45.0, verbose_name='capacidade do tanque (L)')),
                ('gasoline_level', models.FloatField(default=45.0, verbose_name='nível de gasolina (L)')),
                ('fuel_consumption_factor', models.FloatField(default=0.008, verbose_name='fator de consumo (K)')),
                ('total_distance', models.FloatField(default=0.0, verbose_name='distância total (km)')),
                ('trip_consumption', models.FloatField(default=0.0, verbose_name='litros gastos no sistema desde o último abastecimento')),
                ('sync_version', models.PositiveIntegerField(default=0, verbose_name='versão dos dados no backend')),
                ('esp_sync_version', models.PositiveIntegerField(default=0, verbose_name='versão confirmada pela ESP32')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='último envio recebido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(db_index=True, verbose_name='enviado em')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('rpm', models.IntegerField(verbose_name='RPM')),
                ('speed', models.IntegerField(verbose_name='velocidade (km/h)')),
                ('coolant_temp', models.IntegerField(verbose_name='temperatura do arrefecimento (°C)')),
                ('engine_load', models.FloatField(verbose_name='carga do motor (%)')),
                ('throttle_position', models.FloatField(verbose_name='posição do acelerador (%)')),
                ('ltft', models.FloatField(verbose_name='LTFT - correção de combustível de longo prazo (%)')),
                ('timing_advance', models.FloatField(blank=True, null=True, verbose_name='avanço de ignição (°)')),
                ('module_voltage', models.FloatField(blank=True, null=True, verbose_name='tensão do módulo (V)')),
                ('map_pressure', models.FloatField(blank=True, null=True, verbose_name='pressão MAP (kPa)')),
                ('gasoline_level', models.FloatField(verbose_name='nível de gasolina (L)')),
                ('fuel_percent', models.FloatField(verbose_name='combustível (%)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.vehicle')),
            ],
            options={
                'verbose_name': 'leitura',
                'verbose_name_plural': 'leituras',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['vehicle', '-sent_at'], name='telemetry_r_vehicle_a11cc3_idx')],
            },
        ),
    ]
